name: Run PyTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run PyTest
      - name: Run tests
        run: |
          mkdir -p logs
          pytest --maxfail=1 --disable-warnings -q \
                 --html=report.html --self-contained-html

      # Step 5: Upload PyTest HTML report
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: report.html

      # Step 6: Upload log file
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: logs/test.log
